### ISSUE TITLE
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0：对‘TIFFNumberOfDirectories@LIBTIFF_4.0’未定义的引用

### ISSUE THREAD

**Issue by RichardHansir** [qixuxiang/orb-slam2_with_semantic_label#1]
hi,when i make it,it shows 
/usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2.0：对‘TIFFNumberOfDirectories@LIBTIFF_4.0’未定义的引用

How can i fix it?Thansk!

**Comment by qixuxiang** [comment]
Please reply your software and computer system information details,such as ubuntu 16/14,opencv 2/3,etc.

**Comment by RichardHansir** [comment]
My system is ubuntu16.04,installed opencv2.4.9 and opencv3.2,.I change the CMakeLists.txt about opencv, but it didin't work.
The information about opencv in CMakeLists.txt like this
set(OpenCV_DIR "/usr/local/opencv2.4.9/share/OpenCV")
find_package(OpenCV 2.4.9 REQUIRED)
include_directories(
...
${OpenCV_INCLUDE_DIRS} /usr/local/opencv2.4.9/include
...
)

target_link_libraries(${PROJECT_NAME}
...
${OpenCV_LIBS} /usr/local/opencv2.4.9/lib
...
)

**Comment by qixuxiang** [comment]
Well, my suggestion is uninstall opencv3.2 throughly because there will be conflict between the two different opencv version. Also, I test my code only in opencv2.X, not in opencv3.X.

**Comment by qixuxiang** [comment]
Have a good luck!
