### ISSUE TITLE
Error about ORB_SLAM2 testing

### ISSUE THREAD

**Issue by qijixiang** [qixuxiang/orb-slam2_with_semantic_label#17]
After I build ORB_SLAM2 , I want to test it , so I download  "rgbd_dataset_freiburg1_xyz" from "http://vision.in.tum.de/data/datasets/rgbd-dataset/download" . Then I used the command

> ./Examples/Monocular/mono_tumVocabulary/ORBvoc.txt Examples/Monocular/TUM1.yaml Data/rgbd_dataset_freiburg1_xyz

But the system told me there was an error

> bash: ./Examples/Monocular/mono_tumVocabulary/ORBvoc.txt: There is no file or directory

What should I do?
Need Help.

**Comment by EdwiinJunior** [comment]
The file of Vocabulary has a file which need you unzip

**Comment by 13159851972** [comment]
> The file of Vocabulary has a file which need you unzip

Thank you very much.I have already unzip the file,but it still error.But I test another example,there is no error.So I don't care about this question now.

**Comment by qijixiang** [comment]
> The file of Vocabulary has a file which need you unzip

Thank you very much.I have already unzip the file,but it still error.But I test another example,there is no error.So I don't care about this question now.
