### ISSUE TITLE
OpenCV and PCL built with cuda?

### ISSUE THREAD

**Issue by linmeeka** [qixuxiang/orb-slam2_with_semantic_label#19]
Hello!
Do i need to build OpenCV and PCL with cuda? 
Thank you!

**Comment by qixuxiang** [comment]
No, just build and install OpenCV and PCL  as we normally do.

But you need to install cuda and cudnn to run the project. @linmeeka

**Comment by linmeeka** [comment]
> No, just build and install OpenCV and PCL as we normally do.
> 
> But you need to install cuda and cudnn to run the project. @linmeeka

Thank you for your reply!
I installed cuda 9.0 and tried with opencv3.4 and opencv2.4 to run this project, but in the end it all failed.
Can I add your wechat account and ask in detail?
My wechat is 461884867.
Thanks a lot!

**Comment by qixuxiang** [comment]
cuda9.0 may have some conflicts with opencv, you can try cuda8+opencv2+pcl1.8, this is my own environment.

**Comment by linmeeka** [comment]
> cuda9.0 may have some conflicts with opencv, you can try cuda8+opencv2+pcl1.8, this is my own environment.

ok, thank you

**Comment by linmeeka** [comment]
> cuda9.0 may have some conflicts with opencv, you can try cuda8+opencv2+pcl1.8, this is my own environment.

Hi, I change to cuda 8 + opencv 2.4.8 environment, but the error still exists like below:

`ORB-SLAM2 Copyright (C) 2014-2016 Raul Mur-Artal, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: RGB-D

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded in 5.31s
enter constructor
finish dll
start yoloload
finish yoloload
finish yolotrain
create start
load start
cfg:yolov3.cfg
names:coco.names

Camera Parameters: 
- fx: 535.4
- fy: 539.2
- cx: 320.1
- cy: 247.6
- k1: 0
- k2: 0
- p1: 0
- p2: 0
- fps: 30
- color order: RGB (ignored if grayscale)

ORB Extractor Parameters: 
- Number of Features: 1000
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7

Depth Threshold (Close/Far Points): 2.98842

-------
Start processing sequence ...
Images in the sequence: 827

New map created with 718 points
receive a keyframe, id = 1
receive a keyframe, id = 2
receive a keyframe, id = 3
receive a keyframe, id = 4
receive a keyframe, id = 5
receive a keyframe, id = 6
receive a keyframe, id = 7
receive a keyframe, id = 8
./rgbd_tum: : Unknown error -1404238846
[1]    18288 segmentation fault (core dumped)  ./rgbd_tum ../Vocabulary/ORBvoc.txt ../Examples/RGB-D/TUM3.yaml
`

The error message 'Unknown error -1404238846' seems new, what should i do?
By the way, do i need opencv build with ffmpeg module? When i compile opencv 2.4.8 with ffmpeg module it  failed, so i disable it now.
Looking forward for your reply, thank you !

**Comment by qixuxiang** [comment]
Would you please add more PC information,such as ubuntu16/18, gcc version and pcl version, etc. @linmeeka

**Comment by linmeeka** [comment]
@qixuxiang 
I tried on these two environments:
1. Ubuntu16.04, RTX2070, CUDA9.0, OpenCV2.4.13.6, PCL 1.8.0, gcc/g++ 5.4
2. Ubuntu18.04, GTX960, CUDA8.0, OpenCV2.4.13.6, PCL 1.8.0, gcc/g++ 5.5
OpenCV2.4.13.6 build with ffmpeg 2.8.3, and PCL build without CUDA and GPU.
I also tried OpenCV 3.4 and OpenCV2.4.8(without FFmpeg), and all of these attempts end up with segment fault.

**Comment by qixuxiang** [comment]
Give me your wechat here，maybe I can help you @linmeeka

**Comment by linmeeka** [comment]
> Give me your wechat here，maybe I can help you @linmeeka

461884867，thank you!
