### ISSUE TITLE
libcurand.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zbqlalala** [qixuxiang/orb-slam2_with_semantic_label#2]
hello~
I compiled the code and when it run,it just as the topic.
I installed cuda 9.0 and I see cuda>=6.5 in your "readme", but I just have this problem.
`Loading ORB Vocabulary. This could take a while...
Vocabulary loaded in 5.92s
libcurand.so.8.0: cannot open shared object file: No such file or directory
libYOLOv3SE.so not found. or can't load dependency dlls`
My computer is ubuntu 16.04 and I installed cuda9.0, I am wondering whether the environment must be  cuda8.0?

**Comment by qixuxiang** [comment]
Actually, I do not test my code on cuda9.0. In your case, my suggestion is to compille `darknet` at first, which is in `Thirdparty/darknet`folder. When you have `libYOLOv3SE.so`, you can compile the total project. Good luck!

**Comment by zbqlalala** [comment]
> Actually, I do not test my code on cuda9.0. In your case, my suggestion is to compille `darknet` at first, which is in `Thirdparty/darknet`folder. When you have `libYOLOv3SE.so`, you can compile the total project. Good luck!

thx, I just compiled the code in ubuntu16.04,cuda 9.0 cudnn7.1 and opencv 2.4.13, and it works! really thx.

**Comment by qixuxiang** [comment]
Have a nice day, I will update README soon.
