### ISSUE TITLE
How to replace yolov3 with other semantic segmentation models?

### ISSUE THREAD

**Issue by hyclover** [qixuxiang/orb-slam2_with_semantic_label#23]
Hello! I want to combine ORB-SLAM2 and semantic segmentation CNNs to generate a dense semantic map. I found out your great work, so i want to know how to replace yolo in your code with other CNN models such as deeplab? Thanks!

**Comment by qixuxiang** [comment]
In fact, [vayneli](https://github.com/vayneli) has already replaced my yolov3 with torch yolov3, please refer to  [pointcloudmapping.cc](https://github.com/qixuxiang/orb-slam2_with_semantic_label/blob/master/src/pointcloudmapping.cc) for more details.
